"""Backtesting pipeline using VBT Portfolio.from_signals().

Usage
-----
>>> from src.indicators.backtest import run_backtest
>>> pf = run_backtest(close, high, low, volume)
>>> print(pf.stats())
"""

import vectorbtpro as vbt

from src.indicators.signals import generate_signals


def run_backtest(
    close,
    high,
    low,
    volume,
    init_cash=100_000,
    fees=0.001,
    slippage=0.0,
    # Signal params forwarded
    sniper_length=28,
    sniper_ma_type="Jurik Moving Average",
    vzo_length=14,
    vzo_ma_type="Jurik Moving Average",
    use_sniper=True,
    use_vzo=True,
    combine_mode="and",
    **signal_kwargs,
):
    """Run a backtest from signals generated by SniperProX + VZO.

    Returns
    -------
    vbt.Portfolio
    """
    entries, exits = generate_signals(
        close, high, low, volume,
        sniper_length=sniper_length,
        sniper_ma_type=sniper_ma_type,
        vzo_length=vzo_length,
        vzo_ma_type=vzo_ma_type,
        use_sniper=use_sniper,
        use_vzo=use_vzo,
        combine_mode=combine_mode,
        **signal_kwargs,
    )

    pf = vbt.Portfolio.from_signals(
        close=close,
        entries=entries,
        exits=exits,
        init_cash=init_cash,
        fees=fees,
        slippage=slippage,
    )
    return pf
